import localFont from "next/font/local";
import "./globals.css";
import SearchInput from "./SearchInput";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  bg-zinc-900 text-zinc-200`}
      >
        <div className="flex flex-col gap-10 items-center p-6">
        <SearchInput/>
        <div className="flex flex-col items-center w-full">
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
